---
 json_arch: "hycube_original_mem.json"
 json_arch_before_memupdate: 'hycube_original_updatemem.json'
 mapper_subfolder: 'hycube'
 dfg_type: 'PartPred'
 init_II: 4
 numberofbanks: 2
 banksize: 8192
 max_test_samples: 5
 mapping_method: 0
 llvm_debug_type: 'no'

