---
 json_arch: "stdnoc_original_mem.json"
 json_arch_before_memupdate: 'stdnoc_original_updatemem.json'
 mapper_subfolder: 'stdnoc'
 dfg_type: 'PartPred'
 init_II: 0
 numberofbanks: 4
 banksize: 2048
 max_test_samples: 5
 mapping_method: 0
 llvm_debug_type: 'no'

